version: "3.8"

services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise-app
    restart: unless-stopped
    environment:
      - PORT=3000
      - CORS_ORIGINS=*
      - IFRAME_ORIGINS=*
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "3000:3000"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # models
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve & sleep 5 && ollama pull llama3.2 && wait"

volumes:
  ollama_data:
